
graphql:
      servlet:
               mapping: /graphql
               enabled: true
               corsEnabled: true
graphiql:
    mapping: /graphiql
    endpoint: /graphql
    enabled: true
server:
  port: 9010
