version: '3'
services:
  postgres:
    image: 'postgres:10'
    container_name: beerrating-db
    ports:
      - '8432:5432'
    environment:
      - POSTGRES_PASSWORD=becks
      - POSTGRES_USER=karlheinz
      - POSTGRES_DB=beerrating_db
    volumes:
#      - ./init-greeting-db.sql:/docker-entrypoint-initdb.d/init-greeting-db.sql
      - ./db-data:/var/lib/postgresql/data